name: Repository config actions

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  issues:
    types: [opened, reopened, edited, closed]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pull_request_localization:
    # Don`t runs-on ubuntu-latest bind to specific version [ex : ubuntu-24.04]
    # Using a specific version of Ubuntu to ensure consistent environment
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout repository
        # `actions/checkout@v7` Currently using the latest v7 version of the github checkout action
        uses: actions/checkout@v7

      - name: Detect locale and update PR body
        uses: actions/github-script@v9
        with:
          script: |
            const { run } = require('./.github/scripts/update-pr-template.js');
            return run({ github, context, core });
      
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: '1.24'
      
      # - name: Run localization script
      #   run: go run ./.github/scripts/update-pr-template.go
